# Generated by Django 6.0.2 on 2026-04-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0003_visit_delete_visits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='page',
            field=models.CharField(max_length=255),
        ),
    ]
