# Generated by Django 6.0.2 on 2026-04-14 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visits',
            options={'verbose_name_plural': 'Visits'},
        ),
    ]
